/*
** EPITECH PROJECT, 2019
** secondary
** File description:
** signals
*/

#include "strace.h"
#include <signal.h>

const signal_t sig_tab[] = {
    GETNAME(SIGWINCH),
    GETNAME(SIGABRT),
    GETNAME(SIGALRM),
    GETNAME(SIGBUS),
    GETNAME(SIGCHLD),
    GETNAME(SIGCONT),
    GETNAME(SIGFPE),
    GETNAME(SIGHUP),
    GETNAME(SIGILL),
    GETNAME(SIGINT),
    GETNAME(SIGKILL),
    GETNAME(SIGPIPE),
    GETNAME(SIGQUIT),
    GETNAME(SIGSEGV),
    GETNAME(SIGSTOP),
    GETNAME(SIGTERM),
    GETNAME(SIGTSTP),
    GETNAME(SIGTTIN),
    GETNAME(SIGTTOU),
    GETNAME(SIGUSR1),
    GETNAME(SIGUSR2),
    GETNAME(SIGPOLL),
    GETNAME(SIGPROF),
    GETNAME(SIGSYS),
    GETNAME(SIGURG),
    GETNAME(SIGVTALRM),
    GETNAME(SIGXCPU),
    GETNAME(SIGXFSZ)
};